site_name: Elijah Wood's Portfolio
theme:
  name: mkdocs
  color_mode: dark
  use_color_mode_toggle: true

nav:
  - 'index.md'
  - 'music-key-ml.md'
  - 'ttgen.md'
  - 'cookbook_website.md'
  - 'energy_estimates.md'
  - 'about.md'

markdown_extensions:
  - md_in_html

plugins: []